apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: dbt
spec:
  serviceAccountName: dbt-sa
  volumes:
  - name: dbt-pv
    persistentVolumeClaim:
      claimName: dbt-pvc
  containers:
  - name: test-container
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:373.0.0
    command: ["/bin/sh", "-ec", "sleep 10000"]
    volumeMounts:
      - mountPath: "/models"
        name: dbt-pv
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "dbt"
    effect: "NoSchedule"
